@echo off 
echo Setting up the Yamaha Diagnostics Report Generator... 
echo Creating directories... 
mkdir templates uploads downloads 2>nul 
echo Installing dependencies... 
pip install -r requirements.txt 
echo Setup complete! To run the app, double-click run.bat or type 'python app.py' in the terminal. 
